---
title: 'DATA3888_project2'
author: "Siyue Yang 470013692"
date: "08/05/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE,results="hide",message=FALSE,warning=FALSE}
#R codes
library(GEOquery)  
library(R.utils)
library(reshape2)
library(ggplot2)
library(limma)
library(dplyr)
library(cvTools)
library(randomForest)
```

```{r message=FALSE}
#get patients' outcome
clinical_outcome <-getGEO("GSE120396")
clinical_outcome<- clinical_outcome$GSE120396_series_matrix.txt.gz
rejection_status  <- clinical_outcome$characteristics_ch1.1
rejection_status <- unlist(lapply( strsplit(as.character(rejection_status), ": " ) , `[[` , 2)  )
save(rejection_status, file ="rejection_status.rdata")
```

```{r}
#get gene expressions
datadir = "GSE120396_RAW"
# Read in the files
fileNames <- list.files(datadir)
# unzip all the 88 files
for (files in fileNames){
  gunzip(file.path(datadir,files))
}
```

```{r}
# Read in all 88 files to make a table
gse = c()
fileNames <- gsub(".gz","",fileNames) #correct file names
for(i in 1:length(fileNames)){
  temptable <- read.delim(file.path(datadir, fileNames[i]), header=TRUE)
  gse <- cbind(gse, temptable[,2])
  colnames(gse)[i] <- colnames(temptable)[2]
}
rownames(gse) = read.delim(file.path(datadir, fileNames[1]), header=TRUE)[,1]
write.csv(gse, file = "GSE120396_expression_matrix.txt")

gse <- read.csv("GSE120396_expression_matrix.txt", row.names = 1)

```

```{r}
# quick filter to reduce computational time

largevar = apply(gse, 1, var)
ind = which(largevar > quantile(largevar, 0.9))

X = as.matrix(t(gse[ind,]))
y = rejection_status
set.seed(1)
cvK = 5  # number of CV folds
cv_50acc5_rf = c()
cv_acc_rf = c()
n_sim = 25 ## number of repeats
for (i in 1:n_sim) {

  cvSets = cvFolds(nrow(X), cvK)  # permute all the data, into 5 folds
  cv_acc_rf = c()
  for (j in 1:cvK) {
    test_id = cvSets$subsets[cvSets$which == j]
    X_test = X[test_id, ]
    X_train = X[-test_id, ]
    y_test = y[test_id]
    y_train = y[-test_id]
    ## RandomForest
    rf_res <-  randomForest(x = X_train, y = as.factor(y_train))
    fit <- predict(rf_res, X_test)
    cv_acc_rf[j] = table(fit, y_test) %>% diag %>% sum %>% `/`(length(y_test))
  }
  cv_50acc5_rf <- append(cv_50acc5_rf, mean(cv_acc_rf))
} 
cv_50acc5_rf
mean(cv_50acc5_rf)
sd(cv_50acc5_rf)

#code to find which genes are most important
set.seed(1)
rf <- randomForest(x = X, y = as.factor(y))
varImpPlot(rf)
```









